# TCGA临床、DKK1等基因

In [50]:
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 临床数据

In [51]:
df_clinical_cBioPortal = pd.read_csv('../../data/TCGA-LIHC/raw/TCGA-LIHC_clinical_cBioPortalData.csv')
print(df_clinical_cBioPortal.shape)
df_clinical_cBioPortal.head()

(379, 85)


patientId   AGE AJCC_METASTASIS_PATHOLOGIC_PM AJCC_NODES_PATHOLOGIC_PN  \
0  TCGA-BC-4073  73.0                            MX                       N0   
1  TCGA-BC-A10Q  72.0                            MX                       NX   
2  TCGA-BC-A10R  66.0                            MX                       NX   
3  TCGA-BC-A10S  81.0                            MX                       NX   
4  TCGA-BC-A10T  76.0                            MX                       NX   

  AJCC_PATHOLOGIC_TUMOR_STAGE AJCC_STAGING_EDITION AJCC_TUMOR_PATHOLOGIC_PT  \
0                  Stage IIIA                  6th                       T3   
1                         NaN                  5th                       T2   
2                         NaN                  5th                       T3   
3                         NaN                  5th                       T3   
4                         NaN                  5th                       T4   

   BILIRUBIN_TOTAL  BILIRUBIN_TOTAL_NORM_RANGE_LOWER  \
0              0.7                               0.0   
1              0.5                               NaN   
2              NaN                               NaN   
3              0.6                               NaN   
4              0.7                               NaN   

   BILIRUBIN_TOTAL_NORM_RANGE_UPPER  CREATININE_LEVEL_PRERESECTION  \
0                               1.2                            1.5   
1                               NaN                            0.6   
2                               NaN                            0.7   
3                               NaN                            NaN   
4                               NaN                            1.2   

   CREATININE_NORM_RANGE_LOWER  CREATININE_NORM_RANGE_UPPER  \
0                          0.7                          1.3   
1                          0.7                          1.1   
2                          0.7                          1.1   
3                          NaN                          NaN   
4                          NaN                          NaN   

   DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS DEFINITIVE_SURGICAL_PROCEDURE  \
0                                   0.0       Segmentectomy, Multiple   
1                                   0.0            Extended Lobectomy   
2                                   0.0                     Lobectomy   
3                                   0.0       Segmentectomy, Multiple   
4                                   0.0               Other (specify)   

   DFS_MONTHS             DFS_STATUS  ECOG_SCORE               ETHNICITY  \
0       27.89          0:DiseaseFree         0.0  NOT HISPANIC OR LATINO   
1       11.17  1:Recurred/Progressed         NaN  NOT HISPANIC OR LATINO   
2        6.54  1:Recurred/Progressed         NaN  NOT HISPANIC OR LATINO   
3       37.12  1:Recurred/Progressed         NaN  NOT HISPANIC OR LATINO   
4       19.65  1:Recurred/Progressed         NaN  NOT HISPANIC OR LATINO   

   FAMILY_HISTORY_CANCER_NUMBER_RELATIVES FAMILY_HISTORY_OF_CANCER  \
0                                     3.0                      YES   
1                                     1.0                      YES   
2                                     1.0                      YES   
3                                     NaN                       NO   
4                                     NaN                       NO   

  FORM_COMPLETION_DATE GRADE    HISTOLOGICAL_DIAGNOSIS  \
0             12/20/10    G3  Hepatocellular Carcinoma   
1              3/23/11   NaN  Hepatocellular Carcinoma   
2              3/23/11    G2  Hepatocellular Carcinoma   
3              3/23/11    G1  Hepatocellular Carcinoma   
4              3/23/11    G1  Hepatocellular Carcinoma   

  HISTORY_HEPATO_CARCINOMA_RISK_FACTORS HISTORY_NEOADJUVANT_TRTYN  \
0                       Hemochromatosis                        No   
1    No History of Primary Risk Factors                        No   
2    No History of Primary Risk Factors 

#### 病人数 vs 样本数

In [52]:
print(f"病人数={len(df_clinical_cBioPortal['patientId'].unique())}, 样本数={len(df_clinical_cBioPortal['sampleId'].unique())}")

病人数=377, 样本数=379


#### 有两个病人分别对应两个样本

In [53]:
df_clinical_cBioPortal['patientId'].value_counts().head()

TCGA-DD-AACA    2
TCGA-ZS-A9CF    2
TCGA-2Y-A9H0    1
TCGA-ED-A97K    1
TCGA-CC-A7IE    1
Name: patientId, dtype: int64

In [54]:
df_clinical_cBioPortal['sampleId'].value_counts().head()

TCGA-BC-4073-01    1
TCGA-2Y-A9H2-01    1
TCGA-G3-AAV1-01    1
TCGA-G3-AAUZ-01    1
TCGA-ED-A97K-01    1
Name: sampleId, dtype: int64

# KLRB1

In [55]:
if False:
    df_rnaseq = pd.read_csv("TCGA-LIHC\TCGA-LIHC-FPKM.symbol.txt", sep='\t')
    df_rnaseq.columns = map(lambda x: x.replace('.', '-'), df_rnaseq.columns)
    df_rnaseq.set_index('symbol',inplace=True)    
else:
    df_rnaseq = pd.read_csv("../../data/TCGA-LIHC/clean/TCGA-LIHC_tpm_protein_coding_clean.csv")
    df_rnaseq.set_index('gene_name',inplace=True)
    df_rnaseq = np.log2(df_rnaseq + 1)
    
print(df_rnaseq.shape)
df_rnaseq.head()

(16157, 415)


TCGA-G3-A25X-01A-11R-A16W-07  TCGA-DD-AADS-01A-11R-A41C-07  \
gene_name                                                               
TSPAN6                         5.997987                      5.324467   
TNMD                           0.000000                      0.116907   
DPM1                           5.629044                      4.843705   
SCYL3                          1.874709                      0.529534   
C1orf112                       1.389648                      0.058992   

           TCGA-G3-AAV3-01A-11R-A37K-07  TCGA-T1-A6J8-01A-11R-A32O-07  \
gene_name                                                               
TSPAN6                         6.835602                      6.312783   
TNMD                           0.434452                      0.000000   
DPM1                           6.016999                      5.242294   
SCYL3                          2.758003                      2.446249   
C1orf112                       3.702853                      1.165578   

           TCGA-2Y-A9GU-01A-11R-A38B-07  TCGA-2Y-A9HB-01A-11R-A39D-07  \
gene_name                                                               
TSPAN6                         6.343880                      4.930852   
TNMD                           0.000000                      0.054117   
DPM1                           6.247832                      5.908863   
SCYL3                          2.741637                      2.903728   
C1orf112                       1.429504                      1.521625   

           TCGA-DD-A73E-01A-12R-A32O-07  TCGA-EP-A3RK-11A-11R-A22L-07  \
gene_name                                                               
TSPAN6                         5.776796                      5.522418   
TNMD                           0.471705                      0.049142   
DPM1                           6.245262                      5.191779   
SCYL3                          2.868496                      1.886419   
C1orf112                       3.105754                      0.522952   

           TCGA-UB-A7MB-01A-11R-A33R-07  TCGA-DD-A73A-01A-12R-A32O-07  \
gene_name                                                               
TSPAN6                         5.825545                      5.656276   
TNMD                           0.677272                      0.000000   
DPM1                           6.746109                      5.230290   
SCYL3                          3.437394                      1.972581   
C1orf112                       3.205782                      0.688980   

           TCGA-DD-AAEG-01A-11R-A39D-07  TCGA-ED-A8O6-01A-11R-A36F-07  \
gene_name                                                               
TSPAN6                         4.991243                      6.642608   
TNMD                           0.175813                      0.000000   
DPM1                           6.616346                      6.573539   
SCYL3                          3.313534                      2.856148   
C1orf112                       1.392938                      1.736253   

           TCGA-G3-AAV7-01A-11R-A38B-07  TCGA-DD-A1EJ-11A-11R-A155-07  \
gene_name                                                               
TSPAN6                         7.003732                      5.192467   
TNMD                           0.000000                      0.067949   
DPM1                           7.118541                      5.466872   
SCYL3                          3.727053                      2.146728   
C1orf112                       4.028142                      0.827820   

           TCGA-BC-A216-11A-11R-A155-07  TCGA-CC-A7IJ-01A-11R-A33R-07  \
gene_name                                                               
TSPAN6                         5.395190                      5.798118   
TNMD                           0.108552                      0.889783   
DPM1                           4.986737                      6.205096   
SCYL3                          1.303978                      2

### sample_id：样本编号

In [56]:
df_rnaseq_interest = df_rnaseq.loc[['KLRB1'], :].T # ,'ALDH1','OCT4','c-Myc',
df_rnaseq_interest['sample_id'] = [x[:15] for x in df_rnaseq_interest.index]
# df_rnaseq_interest.reset_index(drop=True, inplace=True)
print(f"样本数={len(df_rnaseq_interest['sample_id'].unique())}")
df_rnaseq_interest.head()

样本数=415


gene_name                        KLRB1        sample_id
TCGA-G3-A25X-01A-11R-A16W-07  3.534483  TCGA-G3-A25X-01
TCGA-DD-AADS-01A-11R-A41C-07  2.768981  TCGA-DD-AADS-01
TCGA-G3-AAV3-01A-11R-A37K-07  2.800263  TCGA-G3-AAV3-01
TCGA-T1-A6J8-01A-11R-A32O-07  1.658651  TCGA-T1-A6J8-01
TCGA-2Y-A9GU-01A-11R-A38B-07  1.276923  TCGA-2Y-A9GU-01

### bcr_patient_barcode：患者ID

In [57]:
df_rnaseq_interest['bcr_patient_barcode'] = df_rnaseq_interest.index.map(lambda x: x[:12])
df_rnaseq_interest.head()

gene_name                        KLRB1        sample_id bcr_patient_barcode
TCGA-G3-A25X-01A-11R-A16W-07  3.534483  TCGA-G3-A25X-01        TCGA-G3-A25X
TCGA-DD-AADS-01A-11R-A41C-07  2.768981  TCGA-DD-AADS-01        TCGA-DD-AADS
TCGA-G3-AAV3-01A-11R-A37K-07  2.800263  TCGA-G3-AAV3-01        TCGA-G3-AAV3
TCGA-T1-A6J8-01A-11R-A32O-07  1.658651  TCGA-T1-A6J8-01        TCGA-T1-A6J8
TCGA-2Y-A9GU-01A-11R-A38B-07  1.276923  TCGA-2Y-A9GU-01        TCGA-2Y-A9GU

In [58]:
print(f"病人数={len(df_rnaseq_interest['bcr_patient_barcode'].unique())}, 样本数={len(df_rnaseq_interest['sample_id'].unique())}")

病人数=365, 样本数=415


### 临床数据中病人数比DKK1病人数多

In [59]:
set(df_clinical_cBioPortal['patientId'].unique()) - set(df_rnaseq_interest['bcr_patient_barcode'].unique())

{'TCGA-2V-A95S',
 'TCGA-BW-A5NP',
 'TCGA-BW-A5NQ',
 'TCGA-CC-A9FU',
 'TCGA-CC-A9FV',
 'TCGA-DD-A1E9',
 'TCGA-DD-A3A0',
 'TCGA-DD-AACM',
 'TCGA-DD-AADE',
 'TCGA-DD-AAE8',
 'TCGA-G3-A25W',
 'TCGA-RC-A6M3'}

### Sample：编号01-09为癌症组织，10-19表示正常对照

In [60]:
df_rnaseq_interest['Sample'] = df_rnaseq_interest.index.map(lambda x: x[13:15]).astype(int)
df_rnaseq_interest['Sample'].unique()

array([ 1, 11], dtype=int64)

### Vial：A表示冰冻组织; B表示福尔马林固定石蜡包埋组织。
已被证明用于测序分析的效果不佳，所以不建议使用类似-01B的样本数据

In [61]:
df_rnaseq_interest['Vial'] = df_rnaseq_interest.index.map(lambda x: x[15])
df_rnaseq_interest['Vial'].unique()

array(['A', 'B'], dtype=object)

### Portion：同属于一个患者组织的不同部分的顺序编号，同一组织会分割为100-120mg的部分，分别使用

In [62]:
df_rnaseq_interest['Portion'] = df_rnaseq_interest.index.map(lambda x: x[17:19]).astype(int)
df_rnaseq_interest['Portion'].unique()

array([11, 12, 21,  1,  2, 31, 23, 51, 22], dtype=int64)

### Analyte：分析的分子类型。
对RNA数据来说，Analyte为R的优先级最该，其次是R和T，而对于DNA层面的分析来说，D的优先级最高。

In [63]:
df_rnaseq_interest['Analyte'] = df_rnaseq_interest.index.map(lambda x: x[19])
df_rnaseq_interest['Analyte'].unique()

array(['R'], dtype=object)

In [64]:
df_rnaseq_interest.head()

gene_name                        KLRB1        sample_id bcr_patient_barcode  \
TCGA-G3-A25X-01A-11R-A16W-07  3.534483  TCGA-G3-A25X-01        TCGA-G3-A25X   
TCGA-DD-AADS-01A-11R-A41C-07  2.768981  TCGA-DD-AADS-01        TCGA-DD-AADS   
TCGA-G3-AAV3-01A-11R-A37K-07  2.800263  TCGA-G3-AAV3-01        TCGA-G3-AAV3   
TCGA-T1-A6J8-01A-11R-A32O-07  1.658651  TCGA-T1-A6J8-01        TCGA-T1-A6J8   
TCGA-2Y-A9GU-01A-11R-A38B-07  1.276923  TCGA-2Y-A9GU-01        TCGA-2Y-A9GU   

gene_name                     Sample Vial  Portion Analyte  
TCGA-G3-A25X-01A-11R-A16W-07       1    A       11       R  
TCGA-DD-AADS-01A-11R-A41C-07       1    A       11       R  
TCGA-G3-AAV3-01A-11R-A37K-07       1    A       11       R  
TCGA-T1-A6J8-01A-11R-A32O-07       1    A       11       R  
TCGA-2Y-A9GU-01A-11R-A38B-07       1    A       11       R

## 对于一个患者有多个样本的进行筛选，最后只选一个样本进行分析

### Sample：编号01-09为癌症组织（建议选择）

In [65]:
df_rnaseq_interest['Sample'].unique()

array([ 1, 11], dtype=int64)

In [66]:
df_rnaseq_interest = df_rnaseq_interest[df_rnaseq_interest['Sample'] < 10].copy()
df_rnaseq_interest['Sample'].unique()

array([1], dtype=int64)

In [67]:
df_rnaseq_interest.shape

(365, 7)

In [68]:
print(f"病人数={len(df_rnaseq_interest['bcr_patient_barcode'].unique())}, 样本数={len(df_rnaseq_interest['sample_id'].unique())}")

病人数=365, 样本数=365


In [69]:
df_rnaseq_interest['bcr_patient_barcode'].value_counts().head()

TCGA-G3-A25X    1
TCGA-DD-AADC    1
TCGA-2Y-A9GX    1
TCGA-FV-A2QQ    1
TCGA-DD-AAD6    1
Name: bcr_patient_barcode, dtype: int64

### 如果bcr_patient_barcode，有多个DKK1表达，选择Sample最小的那个

In [70]:
first_Sample_no = df_rnaseq_interest.groupby('bcr_patient_barcode')['Sample'].transform('min')
is_first_Sample = df_rnaseq_interest['Sample'] == first_Sample_no

In [71]:
df_rnaseq_interest = df_rnaseq_interest.loc[is_first_Sample, ['sample_id', 'KLRB1']]
df_rnaseq_interest.shape

(365, 2)

# DKK1和临床数据合并

In [72]:
df_clinical_cBioPortal_KLRB1 = pd.merge(df_clinical_cBioPortal, df_rnaseq_interest, left_on='sampleId', right_on='sample_id', how='inner')
print(df_clinical_cBioPortal_KLRB1.shape)
df_clinical_cBioPortal_KLRB1.set_index(keys='patientId', inplace=True)
df_clinical_cBioPortal_KLRB1.head()

(365, 87)


AGE AJCC_METASTASIS_PATHOLOGIC_PM AJCC_NODES_PATHOLOGIC_PN  \
patientId                                                                   
TCGA-BC-4073  73.0                            MX                       N0   
TCGA-BC-A10Q  72.0                            MX                       NX   
TCGA-BC-A10R  66.0                            MX                       NX   
TCGA-BC-A10S  81.0                            MX                       NX   
TCGA-BC-A10T  76.0                            MX                       NX   

             AJCC_PATHOLOGIC_TUMOR_STAGE AJCC_STAGING_EDITION  \
patientId                                                       
TCGA-BC-4073                  Stage IIIA                  6th   
TCGA-BC-A10Q                         NaN                  5th   
TCGA-BC-A10R                         NaN                  5th   
TCGA-BC-A10S                         NaN                  5th   
TCGA-BC-A10T                         NaN                  5th   

             AJCC_TUMOR_PATHOLOGIC_PT  BILIRUBIN_TOTAL  \
patientId                                                
TCGA-BC-4073                       T3              0.7   
TCGA-BC-A10Q                       T2              0.5   
TCGA-BC-A10R                       T3              NaN   
TCGA-BC-A10S                       T3              0.6   
TCGA-BC-A10T                       T4              0.7   

              BILIRUBIN_TOTAL_NORM_RANGE_LOWER  \
patientId                                        
TCGA-BC-4073                               0.0   
TCGA-BC-A10Q                               NaN   
TCGA-BC-A10R                               NaN   
TCGA-BC-A10S                               NaN   
TCGA-BC-A10T                               NaN   

              BILIRUBIN_TOTAL_NORM_RANGE_UPPER  CREATININE_LEVEL_PRERESECTION  \
patientId                                                                       
TCGA-BC-4073                               1.2                            1.5   
TCGA-BC-A10Q                               NaN                            0.6   
TCGA-BC-A10R                               NaN                            0.7   
TCGA-BC-A10S                               NaN                            NaN   
TCGA-BC-A10T                               NaN                            1.2   

              CREATININE_NORM_RANGE_LOWER  CREATININE_NORM_RANGE_UPPER  \
patientId                                                                
TCGA-BC-4073                          0.7                          1.3   
TCGA-BC-A10Q                          0.7                          1.1   
TCGA-BC-A10R                          0.7                          1.1   
TCGA-BC-A10S                          NaN                          NaN   
TCGA-BC-A10T                          NaN                          NaN   

              DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS  \
patientId                                            
TCGA-BC-4073                                   0.0   
TCGA-BC-A10Q                                   0.0   
TCGA-BC-A10R                                   0.0   
TCGA-BC-A10S                                   0.0   
TCGA-BC-A10T                                   0.0   

             DEFINITIVE_SURGICAL_PROCEDURE  DFS_MONTHS             DFS_STATUS  \
patientId                                                                       
TCGA-BC-4073       Segmentectomy, Multiple       27.89          0:DiseaseFree   
TCGA-BC-A10Q            Extended Lobectomy       11.17  1:Recurred/Progressed   
TCGA-BC-A10R                     Lobectomy        6.54  1:Recurred/Progressed   
TCGA-BC-A10S       Segmentectomy, Multiple       37.12  1:Recurred/Progressed   
TCGA-BC-A10T               Other (specify)       19.65  1:Recurred/Progressed   

              ECOG_SCORE               ETHNICITY  \
patientId                                          
TCGA-BC-4073         0.0  NOT HISPANIC OR LATINO   
TCGA-BC-A10Q         NaN  NOT HISPANIC OR LATINO   
TCGA-BC-A10R       

In [73]:
os.makedirs('../../data/TCGA-LIHC/clean',exist_ok=True)
df_clinical_cBioPortal_KLRB1.to_csv('../../data/TCGA-LIHC/clean/TCGA-LIHC_clinical_cBioPortalData_KLRB1.csv')